---

- hosts: all
  become: true
  tasks:

  - name: install apache httpd and php packages
    tags: always
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: start httpd (CentOS)
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: open port 80/tcp for CentOS
    firewalld:
      service: http
      permanent: yes
      state: enabled
    when: ansible_distribution == "CentOS"
   # notify: Reload Firewalld

#handlers:
  - name: Reload Firewalld
    service:
      name: firewalld
      state: reloaded
    when: ansible_distribution == "CentOS"
